### ISSUE TITLE
Ordering of Branches in ScatterPlot

### ISSUE THREAD

**Issue by cnobre** [cnobre/cnobre.github.io#10]
Still haven't figured out how to correctly order the branches in the s. network so that they follow the same spatial order as they have on the map! Suggestions?

**Comment by alexsb** [comment]
What is the difficulty? If a segment is between 0 and 180 degrees to the main branch it is "below", if its between 180 and 360 degrees it is "above". Instead of the 180-cut-off you could use the angle of the incoming segment for better results.

**Comment by cnobre** [comment]
While that does give me the relation to the main branch, it doesn't solve the issue of ordering all the sub-branches in relation to each other.

**Comment by alexsb** [comment]
Which are easy to order by the size of the angle, e.g., 15 degree is above 30 degree.

**Comment by cnobre** [comment]
Ok, I think I'll need an example for this to become clear. Given this example tree. What is the order in which the code would check the branches to determine the final order (which should be ABCDE)?
![example](https://cloud.githubusercontent.com/assets/4120607/9199379/181cd924-4010-11e5-978d-66cac0a34ef2.png)

**Comment by alexsb** [comment]
![img_20150811_170359](https://cloud.githubusercontent.com/assets/2039375/9201183/f358389a-404b-11e5-89f5-29c3ade6fd7d.jpg)

There are three parts to that algorithm. First you need to decide locally which branch goes where in my example the "thick" line is the main branch (M). The angle between the two segments of M are alpha. The angle between M and 1 are beta, M-2 is gamma, M-3 is delta. since beta and gamma are smaller than alpha it must be in the "bottom" part of the graph. Which one is at the far bottom is also easy to decide: gamma is bigger than beta so it is at the far bottom.

Delta is bigger than alpha, hence 3 is at the "top" of the main branch. 

When you arrive at a simple crossing with only two outgoing branches top/bottom is obviously easy. 

The important step is that you need to backtrack: once you have all the weights and bottom top assignments you have to do a tree traversal. You're looking for an in-order traversal: https://en.wikipedia.org/wiki/Tree_traversal#In-order_.28symmetric.29

The first node of that algorithm is the bottom-most, etc.

**Comment by cnobre** [comment]
Thanks for the explanation! That makes sense :) I'll implement this tonight!

**Comment by cnobre** [comment]
Done! :+1:

**Comment by alexsb** [comment]
How can I test it without being able to define a main branch as discussed in #11 ?

**Comment by cnobre** [comment]
Issue #11 is now partially resolved so you can see the main branch highlighted in red both in the main map and in the scatterplot!
